# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: false
  poem: false
  review_status: true
  collapse_walkthrough: false
  changed_files_summary: false
  sequence_diagrams: false
  assess_linked_issues: false
  related_issues: false
  related_prs: false
  suggested_labels: false
  suggested_reviewers: false
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: false
